# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a200tfbg676-2
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:ac701:part0:1.0 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib C:/Users/HP/TLC_5_lane/TLC_5_lane.srcs/sources_1/new/TLC_design.v
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/HP/TLC_5_lane/TLC_5_lane.cache/wt [current_project]
set_property parent.project_dir C:/Users/HP/TLC_5_lane [current_project]
catch { write_hwdef -file TLC_design.hwdef }
synth_design -top TLC_design -part xc7a200tfbg676-2
write_checkpoint TLC_design.dcp
report_utilization -file TLC_design_utilization_synth.rpt -pb TLC_design_utilization_synth.pb
